### ISSUE TITLE
Dashboard did not even show

### ISSUE THREAD

**Issue by yuanshi4** [fairlearn/fairlearn#484]
#### Describe the issue linked to the documentation

when I was trying to access the dashboard, the user interactive dashboard did not show up, I only see [out]:<fairlearn.widget._fairlearn_dashboard.FairlearnDashboard at 0x7f0206c42cc0>

**Comment by romanlutz** [comment]
Please run 
```python
from fairlearn import show_versions
show_versions()
```
and paste the output here. That should provide us with some information on your context.

It's likely that you need to reload the browser page with the jupyter notebook (assuming you're running one) and rerun the cell with the dashboard. This is an issue a few people have faced.

Tagging @rihorn2 for awareness.

**Comment by yuanshi4** [comment]
![version](https://user-images.githubusercontent.com/60263695/84934672-4871e800-b09d-11ea-9b07-7507644b83ce.jpg)

**Comment by yuanshi4** [comment]
I tried multiple attempts, using show( ) or display( ), the dashboard is still not showing up...Thank you for your help btw!

**Comment by yuanshi4** [comment]
I am working on Jupyter Notebook btw

**Comment by romanlutz** [comment]
Did you try reloading the page before rerunning it?

Can you also tell us which version of Fairlearn you're using? `pip freeze` should tell you

**Comment by yuanshi4** [comment]
Yes, I did, tried reloading multiple times, and even restart kernel and re-run everything.

**Comment by riedgar-ms** [comment]
Which browser/OS is this?

**Comment by yuanshi4** [comment]
Chrome on Windows
Fairlearn version is 0.4.6

**Comment by yuanshi4** [comment]
And the jupyter notebook is on AWS environment (doubt if that matters)

**Comment by riedgar-ms** [comment]
You mean that you have a windows VM in AWS, and you're RDPing to it, and running the notebook there?

**Comment by riedgar-ms** [comment]
Also, what version of Jupyter? As @romanlutz  said, if you could attach your `pip freeze` it would be very helpful.

**Comment by riedgar-ms** [comment]
I've just used the following requirements file:
```
scikit-learn==0.23.1
numpy==1.18.5
scipy==1.4.1
pandas==1.0.4
Cython==0.28.4
matplotlib==3.0.3
fairlearn==0.4.6
```
and then doing a regular install of jupyter (and shap). With that, I can load one of our sample notebooks, and load the dashboard in Chrome.

I'm slightly puzzled by one thing - your output from `show_versions()` above implies that you're running on a Linux box. On my laptop, I get:
```
System:
    python: 3.6.5 |Anaconda, Inc.| (default, Mar 29 2018, 13:32:41) [MSC v.1900 64 bit (AMD64)]
executable: c:\users\riedgar\appdata\local\continuum\miniconda3\envs\bug-testing\python.exe
   machine: Windows-10-10.0.19041-SP0

Python dependencies:
       pip: 20.1.1
setuptools: 47.3.0.post20200616
   sklearn: 0.23.1
     numpy: 1.18.5
     scipy: 1.4.1
    Cython: 0.28.4
    pandas: 1.0.4
matplotlib: 3.0.3
    tempeh: None
```
