### ISSUE TITLE
Running `predictors = sweep.predictors_` does not work in the GridSearch with Census Data notebook example

### ISSUE THREAD

**Issue by leockl** [fairlearn/fairlearn#562]
#### Describe the bug
I am following the GridSearch with Census Data notebook example (https://fairlearn.github.io/auto_examples/plot_grid_search_census.html) but when I tried running the code `predictors = sweep.predictors_` in the notebook example, I get an error.

#### Steps/Code to Reproduce
`predictors = sweep.predictors_`

#### Expected Results
Expected it to run without any errors, as per the notebook example.

#### Actual Results
Getting the following error:
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-14-cb592bed5a23> in <module>
      2           sensitive_features=A_train)
      3 
----> 4 predictors = sweep.predictors_

AttributeError: 'GridSearch' object has no attribute 'predictors_'
```

#### Versions

Please provide the following information:
- OS: Windows
- Browser: Chrome
- Python version: 3.7.6
- Fairlearn version: 0.4.6
- version of Python packages: 
```
System:
    python: 3.7.6 (default, Jan  8 2020, 20:23:39) [MSC v.1916 64 bit (AMD64)]
executable: C:\Users\HP\Anaconda3\python.exe
   machine: Windows-7-6.1.7601-SP1

Python dependencies:
       pip: 20.0.2
setuptools: 46.2.0.post20200511
   sklearn: 0.22.1
     numpy: 1.18.1
     scipy: 1.4.1
    Cython: 0.29.17
    pandas: 1.0.3
matplotlib: 3.1.3
    tempeh: None
```

**EDIT**: It appears this was previously raised here: https://github.com/fairlearn/fairlearn/issues/495. And the solution is to use `predictors = sweep._predictors`. Apologies, I did not see that this issue has been previously raised. In any case, can we update the documentation on this? If not please close this issue.
