### ISSUE TITLE
Creating group metric sets for regression fails

### ISSUE THREAD

**Issue by vladiliescu** [fairlearn/fairlearn#643]
#### Describe the bug

Unable to create group metric set for `regression` prediction types.

#### Steps/Code to Reproduce

Try to create a `regression` group metric set.

```python
dash_dict = _create_group_metric_set(y_true=y,
                                    predictions=y_pred,
                                    sensitive_features=sf,
                                    prediction_type='regression')
```

#### Expected Results
A dictionary containing the group metrics is created.

#### Actual Results
A dictionary containing the group metrics is, however, not created. Instead, we get the error below.

```python
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-24-96aab337f351> in <module>
      9                                     predictions=y_pred,
     10                                     sensitive_features=sf,
---> 11                                     prediction_type='regression')
     12 
     13 

/anaconda/envs/azureml_py36/lib/python3.6/site-packages/fairlearn/metrics/_group_metric_set.py in _create_group_metric_set(y_true, predictions, sensitive_features, prediction_type)
    145         function_dict = BINARY_CLASSIFICATION_METRICS
    146     elif prediction_type == REGRESSION:
--> 147         result[_PREDICTION_TYPE] == _PREDICTION_REGRESSION
    148         function_dict = REGRESSION_METRICS
    149     else:

KeyError: 'predictionType'

```

#### Versions

- OS: Linux
- Browser (if you're reporting a dashboard bug in jupyter): Chrome
- Python version: 3.6.9
- Fairlearn version: 0.4.6
- version of Python packages: 
```

System:
    python: 3.6.9 |Anaconda, Inc.| (default, Jul 30 2019, 19:07:31)  [GCC 7.3.0]
executable: /anaconda/envs/azureml_py36/bin/python
   machine: Linux-4.15.0-1098-azure-x86_64-with-debian-stretch-sid

Python dependencies:
       pip: 20.1.1
setuptools: 50.3.2
   sklearn: 0.22.2.post1
     numpy: 1.18.5
     scipy: 1.5.2
    Cython: 0.29.21
    pandas: 0.25.3
matplotlib: 3.2.1
    tempeh: None
```
