### ISSUE TITLE
cannot import name 'MetricFrame' (again)

### ISSUE THREAD

**Issue by lokijota** [fairlearn/fairlearn#654]
There is another issue open for this error but it's closed and the solution is not clear, hence this one.

#### Describe the bug

I have spun up an Azure Compute Instance VM as part of Azure Machine Learning. This VM already comes installed  with Fairlearn 0.4.6 . I have developed a notebook in JupyterLab training a model, and now want to use Fairlearn to look for gender-related biases.

Following the instructions from here: <https://fairlearn.github.io/v0.5.0/quickstart.html#evaluating-fairness-related-metrics>, when I do either `from fairlearn.metrics import MetricFrame` or `from fairlearn.widget import FairlearnDashboard` I get:

```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-127-d59f0567414f> in <module>
----> 1 from fairlearn.widget import FairlearnDashboard

/anaconda/envs/azureml_py36/lib/python3.6/site-packages/fairlearn/widget/__init__.py in <module>
      4 """Package for the Fairlearn Dashboard widget."""
      5 
----> 6 from ._fairlearn_dashboard import FairlearnDashboard
      7 
      8 

/anaconda/envs/azureml_py36/lib/python3.6/site-packages/fairlearn/widget/_fairlearn_dashboard.py in <module>
      9     _mean_underprediction, _root_mean_squared_error, false_negative_rate,
     10     false_positive_rate, mean_prediction, selection_rate, true_negative_rate)
---> 11 from fairlearn.metrics import MetricFrame
     12 from warnings import warn
     13 

ImportError: cannot import name 'MetricFrame'
```

I have updated to version 0.5.0 with `pip install --upgrade fairlearn`, which succeded with not errors, restarted the kernel, but the error remains.

From the comments in the other bug report, it seems that for this to work the advanced instructions have to be followed from <https://fairlearn.github.io/v0.5.0/contributor_guide/development_process.html#advanced-install>. However this page just says: "Note that the Fairlearn dashboard is built using nodejs and requires additional steps. ", and these steps are not detailed.

I have also seen the link suggesting using Azure Machine Learning for this, but I want to do it on the VM (or, for that matter, my local laptop).

Guidance appreciated.

#### Versions

Fairlearn is 0.5.0 installed from pip.
Python is what came installed in the VM, show versions outputs:

```
System:
    python: 3.6.9 |Anaconda, Inc.| (default, Jul 30 2019, 19:07:31)  [GCC 7.3.0]
executable: /anaconda/envs/azureml_py36/bin/python
   machine: Linux-4.15.0-1100-azure-x86_64-with-debian-stretch-sid

Python dependencies:
       pip: 20.1.1
setuptools: 50.3.0.post20201006
   sklearn: 0.23.2
     numpy: 1.19.2
     scipy: 1.5.2
    Cython: 0.29.21
    pandas: 0.25.3
matplotlib: 3.3.2
    tempeh: 0.1.12
```
