### ISSUE TITLE
BUG: sklearn.confusion_matrix does not work with None anymore

### ISSUE THREAD

**Issue by romanlutz** [fairlearn/fairlearn#963]
#### Describe the bug
The following tests fail in the marked lines: 
- https://github.com/fairlearn/fairlearn/blob/94229647dda802a59bcbfe7f6d64295d64e96efa/test/unit/metrics/test_extra_metrics.py#L420
- https://github.com/fairlearn/fairlearn/blob/94229647dda802a59bcbfe7f6d64295d64e96efa/test/unit/metrics/test_extra_metrics.py#L388
- https://github.com/fairlearn/fairlearn/blob/94229647dda802a59bcbfe7f6d64295d64e96efa/test/unit/metrics/test_extra_metrics.py#L379

This build shows the errors in full detail https://dev.azure.com/fairlearn/Fairlearn/_build/results?buildId=508&view=logs&j=011e1ec8-6569-5e69-4f06-baf193d1351e&t=e41ce7ed-8506-5fe7-0eaa-68d3583c0fff&l=670

As far as I can tell from looking at the error output it seems like sklearn.confusion_matrix is struggling to compare the returned `None` from `unique_labels = [None, pos_label]` with the present values.
```
TypeError: '<' not supported between instances of 'int' and 'NoneType'
``` 
This behavior probably changed in the latest scikit-learn release. We should fix this asap since it's possible people hit this issue after upgrading to latest versions (or with fresh installation), and our tests are failing which prevents us from merging PRs.

#### Steps/Code to Reproduce
Just run `python -m pytest test/unit/metrics` to reproduce

#### Versions
```
System:
    python: 3.8.10 (default, Jun  2 2021, 10:49:15)  [GCC 9.4.0]
executable: /usr/bin/python
   machine: Linux-5.11.0-34-generic-x86_64-with-glibc2.29

Python dependencies:
    Cython: None
matplotlib: 3.4.3
     numpy: 1.21.2
    pandas: 1.3.3
       pip: 20.0.2
     scipy: 1.7.1
setuptools: 45.2.0
   sklearn: 1.0
    tempeh: None
```

FYI @riedgar-ms who wrote a bunch of these tests and @adrinjalali who may know what's wrong with `confusion_matrix` (or rather our way of using it).
