### ISSUE TITLE
TST: CorrelationRemover is failing estimator checks

### ISSUE THREAD

**Issue by romanlutz** [fairlearn/fairlearn#964]
#### Describe the bug

`CorrelationRemover` is failing in our unit tests to check for estimator API compatibility: 
```
TypeError: fit() got an unexpected keyword argument 'sample_weight'
```

In a recent scikit-learn commit the following change occurred: https://github.com/scikit-learn/scikit-learn/commit/cbfbd863804da1005eda2fe8ee34ebe6380f9b3a# 
The important part there is https://github.com/scikit-learn/scikit-learn/commit/cbfbd863804da1005eda2fe8ee34ebe6380f9b3a#diff-49f814863816a0e8d199ba647472450ecc59a4375171db23cb1ca36063d6dc25R876-R888 that is, it doesn't check whether `sample_weight` is an argument on `fit` anymore. This seems to be the root cause.

This is failing tests so we are blocked from merging PRs until it's fixed.

#### Steps/Code to Reproduce
`python -m pytest test/unit/preprocessing`

#### Versions
```
System:
    python: 3.8.10 (default, Jun  2 2021, 10:49:15)  [GCC 9.4.0]
executable: /usr/bin/python
   machine: Linux-5.11.0-34-generic-x86_64-with-glibc2.29

Python dependencies:
    Cython: None
matplotlib: 3.4.3
     numpy: 1.21.2
    pandas: 1.3.3
       pip: 20.0.2
     scipy: 1.7.1
setuptools: 45.2.0
   sklearn: 1.0
    tempeh: None

```

@adrinjalali do you have a good intuition on what the fix here should be? Since that technique doesn't yet support `sample_weight` (and we have no plans of adding that anytime soon) it seems wrong to add the argument just to satisfy this check. Wdyt?
FYI @koaning who added `CorrelationRemover`
